IDD_WEB-master 3/IDD_WEB/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/$', views.index, name='index'),
    url(r'^$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^charts/$', views.charts, name='charts'),
    url(r'^new_mongo_connection/$', views.new_mongo_connection, name='new_mongo_connection'),
    url(r'^new_json_connection/$', views.new_json_connection, name='new_json_connection'),
    url(r'^new_csv_connection/$', views.new_csv_connection, name='new_csv_connection'),
    url(r'^new_excel_connection/$', views.new_excel_connection, name='new_excel_connection'),
    url(r'^view_data/$', views.view_data, name='view_data'),
    url(r'^data_list/$', views.data_list, name='data_list'),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IDD_WEB-master 3/dashboard/urls.py
from django.urls import path, re_path, include
from . import views
from .data_generator import insert_data
from . import dash_app_base_generic   # this loads the Dash app
from . import dash_layouts
from .dash_server import app, server
from django.contrib import admin
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from IDD_WEB import views as IDD_views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/admin/', admin.site.urls),

    re_path('^_dash-', views.dash_ajax),
    path('index/', views.index, name='index'),
    path('test/', views.test, name='test'),
    path('<author_id>/team/', views.dashboard1, name='team'),
    path('<author_id>/player/', views.dashboard2, name='player'),
    path('<author_id>/body/', views.dashboard3, name='body'),
    path('<author_id>/playerload/', views.dashboard4, name='playerload'),
    path('livingstream/', views.livingstream, name='livingstream'),
    path('admin/', admin.site.urls),
    url(r'^index/$', IDD_views.index, name='index'),
    url(r'^$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^charts/$', IDD_views.charts, name='charts'),
    url(r'^new_mongo_connection/$', IDD_views.new_mongo_connection, name='new_mongo_connection'),
    url(r'^new_json_connection/$', IDD_views.new_json_connection, name='new_json_connection'),
    url(r'^new_csv_connection/$', IDD_views.new_csv_connection, name='new_csv_connection'),
    url(r'^new_excel_connection/$', IDD_views.new_excel_connection, name='new_excel_connection'),
    url(r'^view_data/$', IDD_views.view_data, name='view_data'),
    url(r'^data_list/$', IDD_views.data_list, name='data_list'),

]

IDD_WEB-master 3/dashboard/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=100)

IDD_WEB-master 3/dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Author
from .dash_server import dash_dispatcher, clean_dash_content
from django.views.decorators.csrf import csrf_exempt
from .data_generator import insert_data

def index(request):

    # get the list of engagements:
    authors = Author.objects.all()

    # get dash content:
    #print(authors)

    context = {'authors': authors}

    return render(request, 'index.html', context=context)

def test(request):
    return render(request,'test.html',context={})

@csrf_exempt
def dash_ajax(request, **kwargs):
    #print('Function: dash_ajax')
    return HttpResponse(dash_dispatcher(request,), content_type='application/json')


def dashboard1(request, author_id):
    authors = Author.objects.all()

    # get the django context:
    #author = get_object_or_404(Author, pk=author_id)

    # print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'dash.html', context=context)


def dashboard2(request, author_id):
    authors = Author.objects.all()

   # context = {'authors': authors[0]}

    # get the django context:
   # author = get_object_or_404(Author, pk=author_id)

    # print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'dash.html', context=context)

def dashboard3(request, author_id):
    authors = Author.objects.all()

   # context = {'authors': authors[0]}

    # get the django context:
   # author = get_object_or_404(Author, pk=author_id)

    # print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'body.html', context=context)


def dashboard4(request, author_id):
    authors = Author.objects.all()

   # context = {'authors': authors[0]}

    # get the django context:
   # author = get_object_or_404(Author, pk=author_id)

    # print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'playerload.html', context=context)


@csrf_exempt
def livingstream(request):
    if request.is_ajax():
        # print("check,check")
        insert_data()

    return HttpResponse('success')

IDD_WEB-master 3/dashboard/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Axicor Intelligent Data Discoery</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static "dashboard/vendor/bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static "dashboard/vendor/font-awesome/css/font-awesome.min.css" %}">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static "dashboard/css/fontastic.css" %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="{% static "dashboard/css/grasp_mobile_progress_circle-1.0.0.min.css" %}">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="{% static "dashboard/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css" %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static "dashboard/css/style.default.css" %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static "dashboard/css/custom.css" %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static "dashboard/img/favicon.ico" %}">



    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->












  </head>

      <!-- JavaScript files-->
    <script src="{% static "dashboard/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "dashboard/vendor/popper.js/umd/popper.min.js" %}"> </script>
    <script src="{% static "dashboard/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "dashboard/js/grasp_mobile_progress_circle-1.0.0.min.js" %}"></script>
    <script src="{% static "dashboard/vendor/jquery.cookie/jquery.cookie.js" %}"> </script>
    <script src="{% static "dashboard/vendor/chart.js/Chart.min.js" %}"></script>
    <script src="{% static "dashboard/vendor/jquery-validation/jquery.validate.min.js" %}"></script>
    <script src="{% static "dashboard/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <script src="{% static "dashboard/js/charts-home.js" %}"></script>
    <!-- Main File-->
    <script src="{% static "dashboard/js/front.js" %}"></script>














  <body>
    <!-- Side Navbar -->
    <nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">

            <h3 class="h3">Admin</h3><span>Axicor</span>
          </div>
          <!-- Small Brand information, appears on minimized sidebar-->
          <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> HOME</a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
          <h5 class="sidenav-heading">Main Menu</h5>
          <ul id="side-main-menu" class="side-menu list-unstyled">

              <li><a href={% url "index" %}> <i class="icon-home"></i> Home </a></li>
              <li><a href=/dashboard/3/team/> <i class="icon-home"></i>  Data Analysis  </a></li>
              <li><a href="#SportDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Data Analysis  </a>
              <ul id="SportDropdown" class="collapse list-unstyled ">
                  <li><a href=/dashboard/3/team/> <i class="icon-form"></i>Team Analytics </a></li>
                  <li><a href=/dashboard/3/player/> <i class="icon-form"></i>Player Analytics </a></li>
                  <li><a href=/dashboard/3/body/> <i class="icon-form"></i>Body Analytics </a></li>
                  <li><a href=/dashboard/3/playerload/> <i class="icon-form"></i>Playerload Visualisation </a></li>
              </ul>
            </li>
              <li><a href={% url "view_data" %}> <i class="icon-grid"></i> Browse Data  </a></li>
              <li><a href={% url "index" %}> <i class="icon-home"></i>   Dashboard   </a></li>
              <li><a href="#newConnDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>New Connection </a>
              <ul id="newConnDropdown" class="collapse list-unstyled ">
                  <li><a href={% url "new_mongo_connection" %}><i class="icon-form"></i>   PostgreSQL    </a></li>
                  <li><a href={% url "new_mongo_connection" %}><i class="icon-form"></i>   MySQL    </a></li>
                  <li><a href={% url "new_mongo_connection" %}><i class="icon-form"></i>   MongoDB    </a></li>
                  <li><a href={% url "new_csv_connection" %}><i class="icon-form"></i>   CSV    </a></li>
                  <li><a href={% url "new_excel_connection" %}><i class="icon-form"></i>   Excel    </a></li>
                  <li><a href={% url "new_json_connection" %}><i class="icon-form"></i>   Json    </a></li>
              </ul>
            </li>

              <li><a href="#RecentDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Recent Connection </a>
              <ul id="RecentDropdown" class="collapse list-unstyled ">
                  <li><a href={% url "index" %}> <i class="icon-form"></i>Manufacturing <br> &emsp; &emsp; PostgreSQL <br> &emsp; 127.0.0.1:5432 </a></li>
                  <li><a href={% url "index" %}> <i class="icon-form"></i>Sport Analytics <br> &emsp; &emsp; MongoDB<br> &emsp; 127.0.0.1:27017 </a></li>
              </ul>
            </li>

            <li> <a href="#"> <i class="fa fa-bell"></i>Notifications
                <div class="badge badge-warning">6 New</div></a></li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="page">
      <!-- navbar-->
      <header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
                  <div class="brand-text d-none d-md-inline-block"><span> DATABASE </span><strong class="text-primary">DASHBOARD</strong></div></a></div>
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">

                <!-- Notifications dropdown-->
                <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell"></i><span class="badge badge-warning">12</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="icon-interface-windows"></i>You have 6 new logs </div>
                          <div class="notification-time"><small>3 days ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="icon-interface-windows"></i>You have 2 new collections created</div>
                          <div class="notification-time"><small>42 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted</div>
                          <div class="notification-time"><small>10 hours ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="icon-interface-windows"></i>You have 1 new table(s)</div>
                          <div class="notification-time"><small>87 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-bell"></i>view all notifications                                            </strong></a></li>
                  </ul>
                </li>

                <!-- Log out-->
                <li class="nav-item"><a href={% url "login" %}> <span class="d-none d-sm-inline-block">Logout</span><i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

                {% block content %}

                {% endblock %}

                {% block extra_js %}

                {% endblock %}

<!-- Page Footer -->
      <footer class="main-footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <p>Axicor &copy; 2018</p>
            </div>
            <div class="col-sm-6 text-right">
              <p>Powered by <a href="https://bootstrapious.com" class="external"> Axicor </a></p>
              <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

IDD_WEB-master 3/dashboard/templates/body.html
{% extends "base.html" %}
{% load static %}
import dash_core_components as dcc
import dash_html_components as html
from .models import Author
from django.shortcuts import get_object_or_404
import pandas as pd
import plotly.graph_objs as go
import numpy as np

{% block content %}
<script src="http://d3js.org/d3.v3.min.js"></script>
<body class="animsition">

    <div class="page-wrapper">
        <!-- PAGE CONTAINER-->
        <div class="page-container">


            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">OVERVIEW</h2>
                                    <button class="au-btn au-btn-icon au-btn--blue" id="acceptstream">
                                        <i class="zmdi zmdi-plus"></i>Start Recieving Data Stream</button>
                                     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                                    {% csrf_token %}
                                    <script>
                                    $('#acceptstream').click(function(){
                                        $.ajax({
                                        url:'/dashboard/livingstream/',
                                        type:'POST',
                                         data:{'click': 'True'},
                                        success:function(data){
                                            console.log(data)
                                        }
                                        });
                                        });
                                </script>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">

                                  {{ dash_content | safe}}

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2018 Axicor. All rights reserved. Data science by <a href="https://www.axicor.com">Axicor</a>.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>


</body>

{% endblock %}

<!-- end document-->

IDD_WEB-master 3/dashboard/templates/dash.html
{% extends "base.html" %}
{% load static %}
import dash_core_components as dcc
import dash_html_components as html
from .models import Author
from django.shortcuts import get_object_or_404
import pandas as pd
import plotly.graph_objs as go
import numpy as np
{%block content%}



<body class="animsition">
    <div class="page-wrapper">
        <!-- PAGE CONTAINER-->
        <div class="page-container">

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">OVERVIEW</h2>
                                    <button class="au-btn au-btn-icon au-btn--blue" id="acceptstream">
                                        <i class="zmdi zmdi-plus"></i>Start Recieving Data Stream</button>
                                     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                                    {% csrf_token %}
                                    <script>
                                    $('#acceptstream').click(function(){
                                        $.ajax({
                                        url:'/dashboard/livingstream/',
                                        type:'POST',
                                         data:{'click': 'True'},
                                        success:function(data){
                                            console.log(data)
                                        }
                                        });
                                        });
                                </script>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">

                                  {{ dash_content | safe}}

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2018 Axicor. All rights reserved. Data science by <a href="https://www.axicor.com">Axicor</a>.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>


</body>

{% endblock %}
<!-- end document-->

IDD_WEB-master 3/dashboard/templates/dashboard1.html
{% extends "base.html" %}

{% block content %}

      <br>
      <h4>About Author: {{author.name}} </h4>

      <p>Cupcake ipsum dolor sit amet tootsie roll lemon drops. Marzipan gummi bears wafer. Jujubes topping sesame snaps oat cake gummies. Tootsie roll tootsie roll jelly-o dessert croissant</p> <br>

      <a href="{% url 'dashboard:index' %}">Go Back</a> </td>

      <div>
            {{ dash_content | safe}}
      </div>

{% endblock %}

IDD_WEB-master 3/dashboard/templates/dashboard2.html
{% extends "base.html" %}

{% block content %}

      <br>
      <h4>About Author: {{author.name}} </h4>

      <p>Cupcake ipsum dolor sit amet tootsie roll lemon drops. Marzipan gummi bears wafer. Jujubes topping sesame snaps oat cake gummies. Tootsie roll tootsie roll jelly-o dessert croissant</p> <br>

      <a href="{% url 'dashboard:index' %}">Go Back</a> </td>

      <div>

            {{ dash_content | safe}}

      </div>

{% endblock %}

IDD_WEB-master 3/dashboard/templates/index.html
{% extends "base.html" %}

{% block content %}

<table style='width: 1000px'>

    <tr>
        <th>ID</th>
        <th>Author Name</th>
        <th>Link</th>

    {% for author in authors %}

      <tr>
        <td> {{ author.id }} </td>
        <td> {{ author.name }} </td>
        <td>  <a href="{% url 'dashboard:team' author.id %}">Go to Dash </a>
      </tr>
    {% endfor %}

</table>

{% endblock %}

IDD_WEB-master 3/dashboard/templates/playerload.html
{% extends "base.html" %}
{% load static %}
import dash_core_components as dcc
import dash_html_components as html
from .models import Author
from django.shortcuts import get_object_or_404
import pandas as pd
import plotly.graph_objs as go
import numpy as np
{%block content%}



<body class="animsition">
    <div class="page-wrapper">
        <!-- PAGE CONTAINER-->
        <div class="page-container">

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">Playerload Visualisation</h2>

                                     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">

                                  {{ dash_content | safe}}

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2018 Axicor. All rights reserved. Data science by <a href="https://www.axicor.com">Axicor</a>.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>


</body>

{% endblock %}
<!-- end document-->

IDD_WEB-master 3/dashboard/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>

    var canvas = d3.select("body")
                 .append("svg")
                 .attr("width",100)
                 .attr("height",70)
    var circle = canvas.append("circle")
                 .attr("cx",50)
                 .attr("cy",50)
                 .attr("r",20)
                 .attr("fill","red")
                 .attr("opacity","0.3");
    var canvas = d3.select("body")
                 .append("svg")
                 .attr("width",100)
                 .attr("height",70)
                 .attr("")
    var circle = canvas.append("circle")
                 .attr("cx",50)
                 .attr("cy",50)
                 .attr("r",20)
                 .attr("fill","red")
                 .attr("opacity","0.7");
    var canvas = d3.select("body")
                 .append("svg")
                 .attr("width",100)
                 .attr("height",70)
    var circle = canvas.append("circle")
                 .attr("cx",50)
                 .attr("cy",50)
                 .attr("r",20)
                 .attr("fill","red")
                 .attr("opacity","1");
</script>
<p>20%probability   30%probability        40%probability</p>
</body>
</html>